### ISSUE TITLE
issue trying to add simple node

### ISSUE THREAD

**Issue by looooo** [wonderworks-software/PyFlowPyrr#2]
I observe this by adding a simple v3Create node. Not sure if I am doing something wrong.

```
[ERROR 21:22:13]: getInputWidget() got an unexpected keyword argument 'pinAnnotations'
Traceback (most recent call last):
File "/home/k/projects/PyFlow/PyFlow/App.py", line 221, in onRequestFillProperties
toolInstance.assignPropertiesWidget(propertiesFillDelegate)
File "/home/k/projects/PyFlow/PyFlow/Packages/PyFlowBase/Tools/PropertiesTool.py", line 58, in assignPropertiesWidget
propertiesFillDelegate(self.propertiesWidget)
File "/home/k/projects/PyFlow/PyFlow/UI/Canvas/UINodeBase.py", line 1271, in createPropertiesWidget
self.createInputWidgets(inputsCategory)
File "/home/k/projects/PyFlow/PyFlow/UI/Canvas/UINodeBase.py", line 1290, in createInputWidgets
w = createInputWidget(inp.dataType, dataSetter, inp.defaultValue(), inp.getInputWidgetVariant(), pinAnnotations=inp._rawPin.annotationDescriptionDict)
File "/home/k/projects/PyFlow/PyFlow/UI/Widgets/InputWidgets.py", line 128, in createInputWidget
pinInputWidget = factory(dataType, dataSetter, defaultValue, widgetVariant, **kwds)
TypeError: getInputWidget() got an unexpected keyword argument 'pinAnnotations'
```

**Comment by looooo** [comment]
It still doesn't work for me (ubuntu 18.04 in conda py37/qt5.9 environement) This issue also occurs with other nodes from PyFlowBase (eg.: colorRamp).

**Comment by looooo** [comment]
Ah, colorRamp has a different error:

```
[ERROR 09:47:37]: 'FloatInputWidgetSimple' object has no attribute 'setMinimum'
Traceback (most recent call last):
File "/home/k/projects/PyFlow/PyFlow/App.py", line 221, in onRequestFillProperties
toolInstance.assignPropertiesWidget(propertiesFillDelegate)
File "/home/k/projects/PyFlow/PyFlow/Packages/PyFlowBase/Tools/PropertiesTool.py", line 58, in assignPropertiesWidget
propertiesFillDelegate(self.propertiesWidget)
File "/home/k/projects/PyFlow/PyFlow/UI/Canvas/UINodeBase.py", line 1271, in createPropertiesWidget
self.createInputWidgets(inputsCategory)
File "/home/k/projects/PyFlow/PyFlow/Packages/PyFlowBase/UI/UIColorRamp.py", line 65, in createInputWidgets
inputVal.setMinimum(0.0)
AttributeError: 'FloatInputWidgetSimple' object has no attribute 'setMinimum'
```

The previously reported error is indeed fixed. Sorry for the confusion.

**Comment by IlgarLunin** [comment]
yes. and i just fixed it. try

**Comment by looooo** [comment]
I can confirm, both issues are fixed. Thanks!
